/** Hex to HSL */
export function hexToHsl(hex: string): [number, number, number] {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;

  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = ((g - b) / d + (g < b ? 6 : 0)) / 6; break;
      case g: h = ((b - r) / d + 2) / 6; break;
      case b: h = ((r - g) / d + 4) / 6; break;
    }
  }

  return [Math.round(h * 360), Math.round(s * 100), Math.round(l * 100)];
}

/** HSL to Hex */
export function hslToHex(h: number, s: number, l: number): string {
  const sn = s / 100;
  const ln = l / 100;

  const c = (1 - Math.abs(2 * ln - 1)) * sn;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = ln - c / 2;

  let r = 0, g = 0, b = 0;
  if (h < 60) { r = c; g = x; }
  else if (h < 120) { r = x; g = c; }
  else if (h < 180) { g = c; b = x; }
  else if (h < 240) { g = x; b = c; }
  else if (h < 300) { r = x; b = c; }
  else { r = c; b = x; }

  const toHex = (v: number) => Math.round((v + m) * 255).toString(16).padStart(2, "0");
  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}

/** Açık mod renklerinden koyu mod renkleri otomatik üret */
export function autoGenerateDarkColors(
  lightColors: Record<string, string>
): Record<string, string> {
  const dark: Record<string, string> = {};

  // Primary renkleri daha açık yap
  if (lightColors.theme_color_primary) {
    const [h, s, l] = hexToHsl(lightColors.theme_color_primary);
    dark.theme_dark_color_primary = hslToHex(h, Math.min(s + 10, 100), Math.min(l + 15, 85));
    dark.theme_dark_color_primary_dark = hslToHex(h, s, l);
    dark.theme_dark_color_primary_light = hslToHex(h, Math.min(s + 5, 100), Math.min(l + 25, 90));
  }

  // Secondary
  if (lightColors.theme_color_secondary) {
    const [h, s, l] = hexToHsl(lightColors.theme_color_secondary);
    dark.theme_dark_color_secondary = hslToHex(h, Math.max(s - 10, 0), Math.min(l + 20, 85));
  }

  // Background → koyu
  if (lightColors.theme_color_foreground) {
    dark.theme_dark_color_background = lightColors.theme_color_foreground;
  }

  // Foreground → açık
  if (lightColors.theme_color_muted) {
    dark.theme_dark_color_foreground = lightColors.theme_color_muted;
  }

  // Muted background → koyu muted
  if (lightColors.theme_color_foreground) {
    const [h, s] = hexToHsl(lightColors.theme_color_foreground);
    dark.theme_dark_color_muted = hslToHex(h, s, 15);
  }

  // Muted foreground
  if (lightColors.theme_color_muted_foreground) {
    const [h, s, l] = hexToHsl(lightColors.theme_color_muted_foreground);
    dark.theme_dark_color_muted_foreground = hslToHex(h, Math.max(s - 10, 0), Math.min(l + 20, 85));
  }

  // Border
  if (lightColors.theme_color_foreground) {
    const [h, s] = hexToHsl(lightColors.theme_color_foreground);
    dark.theme_dark_color_border = hslToHex(h, s, 25);
  }

  // Card
  if (lightColors.theme_color_foreground) {
    const [h, s] = hexToHsl(lightColors.theme_color_foreground);
    dark.theme_dark_color_card = hslToHex(h, s, 15);
  }

  // Card foreground
  if (lightColors.theme_color_muted) {
    dark.theme_dark_color_card_foreground = lightColors.theme_color_muted;
  }

  // Status renkler
  dark.theme_dark_color_success = "#4ade80";
  dark.theme_dark_color_warning = "#fbbf24";
  dark.theme_dark_color_danger = "#f87171";
  dark.theme_dark_color_info = "#22d3ee";

  return dark;
}

/** CSS değişken adı mapping */
export const COLOR_CSS_MAP: Record<string, string> = {
  theme_color_primary: "--color-primary",
  theme_color_primary_dark: "--color-primary-dark",
  theme_color_primary_light: "--color-primary-light",
  theme_color_secondary: "--color-secondary",
  theme_color_background: "--color-background",
  theme_color_foreground: "--color-foreground",
  theme_color_muted: "--color-muted",
  theme_color_muted_foreground: "--color-muted-foreground",
  theme_color_border: "--color-border",
  theme_color_card: "--color-card",
  theme_color_card_foreground: "--color-card-foreground",
  theme_color_success: "--color-success",
  theme_color_warning: "--color-warning",
  theme_color_danger: "--color-danger",
  theme_color_info: "--color-info",
};

export const DARK_COLOR_CSS_MAP: Record<string, string> = {
  theme_dark_color_primary: "--color-primary",
  theme_dark_color_primary_dark: "--color-primary-dark",
  theme_dark_color_primary_light: "--color-primary-light",
  theme_dark_color_secondary: "--color-secondary",
  theme_dark_color_background: "--color-background",
  theme_dark_color_foreground: "--color-foreground",
  theme_dark_color_muted: "--color-muted",
  theme_dark_color_muted_foreground: "--color-muted-foreground",
  theme_dark_color_border: "--color-border",
  theme_dark_color_card: "--color-card",
  theme_dark_color_card_foreground: "--color-card-foreground",
  theme_dark_color_success: "--color-success",
  theme_dark_color_warning: "--color-warning",
  theme_dark_color_danger: "--color-danger",
  theme_dark_color_info: "--color-info",
};
