export interface ThemePreset {
  id: string;
  name: string;
  description: string;
  preview: {
    primaryColor: string;
    backgroundColor: string;
    foregroundColor: string;
  };
  settings: Record<string, string>;
}

const BASE_LAYOUT = {
  theme_header_style: "default",
  theme_footer_style: "default",
  theme_product_card_style: "default",
  theme_product_grid_columns: "4",
  theme_border_radius: "lg",
  theme_container_width: "1280",
  theme_dark_mode_enabled: "true",
  theme_custom_css: "",
  theme_font_size_base: "16px",
  theme_font_weight_body: "400",
  theme_font_heading_family: "",
};

const BASE_STATUS_COLORS = {
  theme_color_success: "#22c55e",
  theme_color_warning: "#f59e0b",
  theme_color_danger: "#ef4444",
  theme_color_info: "#06b6d4",
  theme_dark_color_success: "#4ade80",
  theme_dark_color_warning: "#fbbf24",
  theme_dark_color_danger: "#f87171",
  theme_dark_color_info: "#22d3ee",
};

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: "default",
    name: "Varsayilan Mavi",
    description: "Modern ve profesyonel mavi tema",
    preview: { primaryColor: "#2563eb", backgroundColor: "#ffffff", foregroundColor: "#0f172a" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "default",
      theme_font_family: "Inter",
      theme_color_primary: "#2563eb",
      theme_color_primary_dark: "#1d4ed8",
      theme_color_primary_light: "#3b82f6",
      theme_color_secondary: "#64748b",
      theme_color_background: "#ffffff",
      theme_color_foreground: "#0f172a",
      theme_color_muted: "#f1f5f9",
      theme_color_muted_foreground: "#64748b",
      theme_color_border: "#e2e8f0",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#0f172a",
      theme_dark_color_primary: "#3b82f6",
      theme_dark_color_primary_dark: "#2563eb",
      theme_dark_color_primary_light: "#60a5fa",
      theme_dark_color_secondary: "#94a3b8",
      theme_dark_color_background: "#0f172a",
      theme_dark_color_foreground: "#f1f5f9",
      theme_dark_color_muted: "#1e293b",
      theme_dark_color_muted_foreground: "#94a3b8",
      theme_dark_color_border: "#334155",
      theme_dark_color_card: "#1e293b",
      theme_dark_color_card_foreground: "#f1f5f9",
    },
  },
  {
    id: "warm-orange",
    name: "Sicak Turuncu",
    description: "Enerjik ve sicak tonlarda turuncu tema",
    preview: { primaryColor: "#ea580c", backgroundColor: "#fffbeb", foregroundColor: "#1c1917" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "warm-orange",
      theme_font_family: "Poppins",
      theme_header_style: "centered",
      theme_color_primary: "#ea580c",
      theme_color_primary_dark: "#c2410c",
      theme_color_primary_light: "#f97316",
      theme_color_secondary: "#78716c",
      theme_color_background: "#fffbeb",
      theme_color_foreground: "#1c1917",
      theme_color_muted: "#fef3c7",
      theme_color_muted_foreground: "#78716c",
      theme_color_border: "#fed7aa",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#1c1917",
      theme_dark_color_primary: "#f97316",
      theme_dark_color_primary_dark: "#ea580c",
      theme_dark_color_primary_light: "#fb923c",
      theme_dark_color_secondary: "#a8a29e",
      theme_dark_color_background: "#1c1917",
      theme_dark_color_foreground: "#fef3c7",
      theme_dark_color_muted: "#292524",
      theme_dark_color_muted_foreground: "#a8a29e",
      theme_dark_color_border: "#44403c",
      theme_dark_color_card: "#292524",
      theme_dark_color_card_foreground: "#fef3c7",
    },
  },
  {
    id: "elegant-dark",
    name: "Zarif Koyu",
    description: "Sofistike ve sik koyu tonlu tema",
    preview: { primaryColor: "#a78bfa", backgroundColor: "#f8fafc", foregroundColor: "#1e1b4b" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "elegant-dark",
      theme_font_family: "Montserrat",
      theme_header_style: "minimal",
      theme_border_radius: "md",
      theme_color_primary: "#a78bfa",
      theme_color_primary_dark: "#8b5cf6",
      theme_color_primary_light: "#c4b5fd",
      theme_color_secondary: "#6b7280",
      theme_color_background: "#f8fafc",
      theme_color_foreground: "#1e1b4b",
      theme_color_muted: "#f1f5f9",
      theme_color_muted_foreground: "#6b7280",
      theme_color_border: "#e2e8f0",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#1e1b4b",
      theme_dark_color_primary: "#c4b5fd",
      theme_dark_color_primary_dark: "#a78bfa",
      theme_dark_color_primary_light: "#ddd6fe",
      theme_dark_color_secondary: "#9ca3af",
      theme_dark_color_background: "#0f0d1a",
      theme_dark_color_foreground: "#f1f5f9",
      theme_dark_color_muted: "#1e1b2e",
      theme_dark_color_muted_foreground: "#9ca3af",
      theme_dark_color_border: "#312e4a",
      theme_dark_color_card: "#1e1b2e",
      theme_dark_color_card_foreground: "#f1f5f9",
    },
  },
  {
    id: "nature-green",
    name: "Doga Yesili",
    description: "Dogal ve taze yesil tonlarinda tema",
    preview: { primaryColor: "#16a34a", backgroundColor: "#fefce8", foregroundColor: "#14532d" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "nature-green",
      theme_font_family: "Nunito",
      theme_product_card_style: "detailed",
      theme_color_primary: "#16a34a",
      theme_color_primary_dark: "#15803d",
      theme_color_primary_light: "#22c55e",
      theme_color_secondary: "#65a30d",
      theme_color_background: "#fefce8",
      theme_color_foreground: "#14532d",
      theme_color_muted: "#ecfccb",
      theme_color_muted_foreground: "#4d7c0f",
      theme_color_border: "#bef264",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#14532d",
      theme_dark_color_primary: "#22c55e",
      theme_dark_color_primary_dark: "#16a34a",
      theme_dark_color_primary_light: "#4ade80",
      theme_dark_color_secondary: "#84cc16",
      theme_dark_color_background: "#0a1f0d",
      theme_dark_color_foreground: "#ecfccb",
      theme_dark_color_muted: "#14532d",
      theme_dark_color_muted_foreground: "#84cc16",
      theme_dark_color_border: "#1a5c2e",
      theme_dark_color_card: "#14532d",
      theme_dark_color_card_foreground: "#ecfccb",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    description: "Sade ve temiz gri tonlarinda tema",
    preview: { primaryColor: "#18181b", backgroundColor: "#ffffff", foregroundColor: "#18181b" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "minimal",
      theme_font_family: "Inter",
      theme_header_style: "minimal",
      theme_footer_style: "minimal",
      theme_product_card_style: "minimal",
      theme_border_radius: "sm",
      theme_color_primary: "#18181b",
      theme_color_primary_dark: "#09090b",
      theme_color_primary_light: "#3f3f46",
      theme_color_secondary: "#71717a",
      theme_color_background: "#ffffff",
      theme_color_foreground: "#18181b",
      theme_color_muted: "#f4f4f5",
      theme_color_muted_foreground: "#71717a",
      theme_color_border: "#e4e4e7",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#18181b",
      theme_dark_color_primary: "#fafafa",
      theme_dark_color_primary_dark: "#e4e4e7",
      theme_dark_color_primary_light: "#ffffff",
      theme_dark_color_secondary: "#a1a1aa",
      theme_dark_color_background: "#09090b",
      theme_dark_color_foreground: "#fafafa",
      theme_dark_color_muted: "#18181b",
      theme_dark_color_muted_foreground: "#a1a1aa",
      theme_dark_color_border: "#27272a",
      theme_dark_color_card: "#18181b",
      theme_dark_color_card_foreground: "#fafafa",
    },
  },
  {
    id: "luxury-gold",
    name: "Luks Altin",
    description: "Premium ve luks altin tonlarinda tema",
    preview: { primaryColor: "#d97706", backgroundColor: "#fffbeb", foregroundColor: "#1c1917" },
    settings: {
      ...BASE_LAYOUT,
      ...BASE_STATUS_COLORS,
      theme_active_preset: "luxury-gold",
      theme_font_family: "Open Sans",
      theme_font_heading_family: "Playfair Display",
      theme_border_radius: "md",
      theme_color_primary: "#d97706",
      theme_color_primary_dark: "#b45309",
      theme_color_primary_light: "#f59e0b",
      theme_color_secondary: "#78716c",
      theme_color_background: "#fffbeb",
      theme_color_foreground: "#1c1917",
      theme_color_muted: "#fef3c7",
      theme_color_muted_foreground: "#78716c",
      theme_color_border: "#fde68a",
      theme_color_card: "#ffffff",
      theme_color_card_foreground: "#1c1917",
      theme_dark_color_primary: "#f59e0b",
      theme_dark_color_primary_dark: "#d97706",
      theme_dark_color_primary_light: "#fbbf24",
      theme_dark_color_secondary: "#a8a29e",
      theme_dark_color_background: "#1c1917",
      theme_dark_color_foreground: "#fef3c7",
      theme_dark_color_muted: "#292524",
      theme_dark_color_muted_foreground: "#a8a29e",
      theme_dark_color_border: "#44403c",
      theme_dark_color_card: "#292524",
      theme_dark_color_card_foreground: "#fef3c7",
    },
  },
];

export const AVAILABLE_FONTS = [
  "Inter",
  "Poppins",
  "Roboto",
  "Open Sans",
  "Montserrat",
  "Nunito",
  "Lato",
  "Raleway",
  "Playfair Display",
  "Merriweather",
];

export function getPresetById(id: string): ThemePreset | undefined {
  return THEME_PRESETS.find((p) => p.id === id);
}

/** All theme setting keys */
export const ALL_THEME_KEYS = Object.keys(THEME_PRESETS[0].settings);
