"use client";

import { useState } from "react";
import { THEME_PRESETS, AVAILABLE_FONTS } from "@/lib/theme-presets";
import { autoGenerateDarkColors } from "@/lib/theme-utils";

const TABS = [
  { id: "presets", label: "Hazir Temalar" },
  { id: "colors", label: "Renkler" },
  { id: "typography", label: "Yazitipi" },
  { id: "layout", label: "Yerlesim" },
  { id: "advanced", label: "Gelismis" },
];

const LIGHT_COLOR_KEYS = [
  { key: "theme_color_primary", label: "Ana Renk" },
  { key: "theme_color_primary_dark", label: "Ana Renk (Koyu)" },
  { key: "theme_color_primary_light", label: "Ana Renk (Acik)" },
  { key: "theme_color_secondary", label: "Ikincil Renk" },
  { key: "theme_color_background", label: "Arka Plan" },
  { key: "theme_color_foreground", label: "Yazi Rengi" },
  { key: "theme_color_muted", label: "Soluk Arka Plan" },
  { key: "theme_color_muted_foreground", label: "Soluk Yazi" },
  { key: "theme_color_border", label: "Kenarlik" },
  { key: "theme_color_card", label: "Kart Arka Plan" },
  { key: "theme_color_card_foreground", label: "Kart Yazi" },
  { key: "theme_color_success", label: "Basari" },
  { key: "theme_color_warning", label: "Uyari" },
  { key: "theme_color_danger", label: "Tehlike" },
  { key: "theme_color_info", label: "Bilgi" },
];

const DARK_COLOR_KEYS = LIGHT_COLOR_KEYS.map((c) => ({
  key: c.key.replace("theme_color_", "theme_dark_color_"),
  label: c.label,
}));

const HEADER_STYLES = [
  { id: "default", label: "Standart", desc: "Logo sol, arama ortada" },
  { id: "centered", label: "Ortali", desc: "Logo ortalanmis, arama altta" },
  { id: "minimal", label: "Minimal", desc: "Tek satir, sade gorunum" },
];

const FOOTER_STYLES = [
  { id: "default", label: "Standart", desc: "4 sutunlu genis footer" },
  { id: "compact", label: "Kompakt", desc: "2 sutun, yan yana" },
  { id: "minimal", label: "Minimal", desc: "Tek satir, sadece linkler" },
];

const CARD_STYLES = [
  { id: "default", label: "Standart", desc: "Hover efektli kart" },
  { id: "minimal", label: "Minimal", desc: "Sade, efektsiz kart" },
  { id: "detailed", label: "Detayli", desc: "Marka, puan ve sepet butonu" },
];

const RADIUS_OPTIONS = [
  { id: "none", label: "Yok" },
  { id: "sm", label: "Kucuk" },
  { id: "md", label: "Orta" },
  { id: "lg", label: "Buyuk" },
  { id: "full", label: "Tam" },
];

interface Props {
  initialSettings: Record<string, string>;
}

export default function ThemeEditorForm({ initialSettings }: Props) {
  const [settings, setSettings] = useState<Record<string, string>>(() => {
    if (Object.keys(initialSettings).length > 0) return initialSettings;
    return THEME_PRESETS[0].settings;
  });
  const [activeTab, setActiveTab] = useState("presets");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [colorMode, setColorMode] = useState<"light" | "dark">("light");

  function update(key: string, value: string) {
    setSettings((prev) => ({ ...prev, [key]: value }));
    setSaved(false);
  }

  function applyPreset(presetId: string) {
    const preset = THEME_PRESETS.find((p) => p.id === presetId);
    if (preset) {
      setSettings(preset.settings);
      setSaved(false);
    }
  }

  function autoGenerateDark() {
    const lightColors: Record<string, string> = {};
    for (const c of LIGHT_COLOR_KEYS) {
      if (settings[c.key]) lightColors[c.key] = settings[c.key];
    }
    const darkColors = autoGenerateDarkColors(lightColors);
    setSettings((prev) => ({ ...prev, ...darkColors }));
    setSaved(false);
  }

  async function handleSave() {
    setSaving(true);
    try {
      const allSettings = Object.entries(settings).map(([key, value]) => ({
        key,
        value,
        group: "theme",
      }));
      const res = await fetch("/api/settings", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ settings: allSettings }),
      });
      if (res.ok) {
        setSaved(true);
        setTimeout(() => setSaved(false), 3000);
      }
    } catch {
    } finally {
      setSaving(false);
    }
  }

  function handleExport() {
    const blob = new Blob([JSON.stringify(settings, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "pixfora-theme.json"; a.click();
    URL.revokeObjectURL(url);
  }

  function handleImport(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const imported = JSON.parse(ev.target?.result as string);
        if (typeof imported === "object") {
          setSettings(imported);
          setSaved(false);
        }
      } catch {}
    };
    reader.readAsText(file);
  }

  return (
    <div className="space-y-6">
      {/* Tabs */}
      <div className="flex gap-1 border-b border-border overflow-x-auto">
        {TABS.map((tab) => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            className={`px-4 py-2.5 text-sm font-medium whitespace-nowrap transition-colors ${
              activeTab === tab.id ? "text-primary border-b-2 border-primary" : "text-muted-foreground hover:text-foreground"
            }`}>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Presets Tab */}
      {activeTab === "presets" && (
        <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
          {THEME_PRESETS.map((preset) => (
            <button key={preset.id} onClick={() => applyPreset(preset.id)}
              className={`p-4 rounded-xl border-2 text-left transition-all ${
                settings.theme_active_preset === preset.id ? "border-primary shadow-lg" : "border-border hover:border-primary/50"
              }`}>
              <div className="flex gap-2 mb-3">
                <div className="w-8 h-8 rounded-full border-2 border-white shadow" style={{ backgroundColor: preset.preview.primaryColor }} />
                <div className="w-8 h-8 rounded-full border-2 border-white shadow" style={{ backgroundColor: preset.preview.backgroundColor }} />
                <div className="w-8 h-8 rounded-full border-2 border-white shadow" style={{ backgroundColor: preset.preview.foregroundColor }} />
              </div>
              <h3 className="font-semibold text-sm">{preset.name}</h3>
              <p className="text-xs text-muted-foreground mt-1">{preset.description}</p>
              {settings.theme_active_preset === preset.id && (
                <span className="inline-block mt-2 px-2 py-0.5 bg-primary/10 text-primary text-xs rounded">Aktif</span>
              )}
            </button>
          ))}
        </div>
      )}

      {/* Colors Tab */}
      {activeTab === "colors" && (
        <div className="space-y-6">
          <div className="flex gap-2">
            <button onClick={() => setColorMode("light")}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${colorMode === "light" ? "bg-primary text-white" : "bg-muted text-muted-foreground"}`}>
              Acik Mod
            </button>
            <button onClick={() => setColorMode("dark")}
              className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${colorMode === "dark" ? "bg-primary text-white" : "bg-muted text-muted-foreground"}`}>
              Koyu Mod
            </button>
            {colorMode === "dark" && (
              <button onClick={autoGenerateDark}
                className="ml-auto px-4 py-2 border border-border rounded-lg text-sm hover:bg-muted transition-colors">
                Otomatik Uret
              </button>
            )}
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
            {(colorMode === "light" ? LIGHT_COLOR_KEYS : DARK_COLOR_KEYS).map((c) => (
              <div key={c.key} className="space-y-1.5">
                <label className="text-xs font-medium text-muted-foreground">{c.label}</label>
                <div className="flex items-center gap-2">
                  <input type="color" value={settings[c.key] || "#000000"}
                    onChange={(e) => update(c.key, e.target.value)}
                    className="w-10 h-10 rounded-lg border border-border cursor-pointer" />
                  <input type="text" value={settings[c.key] || ""}
                    onChange={(e) => update(c.key, e.target.value)}
                    className="flex-1 px-2 py-1.5 border border-border rounded text-xs font-mono bg-background" placeholder="#000000" />
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Typography Tab */}
      {activeTab === "typography" && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium mb-2 block">Govde Yazitipi</label>
              <select value={settings.theme_font_family || "Inter"}
                onChange={(e) => update("theme_font_family", e.target.value)}
                className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-background">
                {AVAILABLE_FONTS.map((f) => <option key={f} value={f}>{f}</option>)}
              </select>
              <p className="text-xs text-muted-foreground mt-1" style={{ fontFamily: settings.theme_font_family || "Inter" }}>
                Ornek yazi: Pixfora ile kolay alisveris deneyimi.
              </p>
            </div>

            <div>
              <label className="text-sm font-medium mb-2 block">Baslik Yazitipi (opsiyonel)</label>
              <select value={settings.theme_font_heading_family || ""}
                onChange={(e) => update("theme_font_heading_family", e.target.value)}
                className="w-full px-3 py-2 border border-border rounded-lg text-sm bg-background">
                <option value="">Govde ile ayni</option>
                {AVAILABLE_FONTS.map((f) => <option key={f} value={f}>{f}</option>)}
              </select>
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <label className="text-sm font-medium mb-2 block">Yazi Boyutu</label>
              <div className="flex gap-2">
                {["14px", "15px", "16px", "17px"].map((size) => (
                  <button key={size} onClick={() => update("theme_font_size_base", size)}
                    className={`px-4 py-2 rounded-lg text-sm border transition-colors ${
                      (settings.theme_font_size_base || "16px") === size ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:border-primary/50"
                    }`}>{size}</button>
                ))}
              </div>
            </div>

            <div>
              <label className="text-sm font-medium mb-2 block">Yazi Kalinligi</label>
              <div className="flex gap-2">
                {[
                  { value: "300", label: "Ince" },
                  { value: "400", label: "Normal" },
                  { value: "500", label: "Orta" },
                ].map((w) => (
                  <button key={w.value} onClick={() => update("theme_font_weight_body", w.value)}
                    className={`px-4 py-2 rounded-lg text-sm border transition-colors ${
                      (settings.theme_font_weight_body || "400") === w.value ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground hover:border-primary/50"
                    }`} style={{ fontWeight: Number(w.value) }}>{w.label}</button>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Layout Tab */}
      {activeTab === "layout" && (
        <div className="space-y-8">
          {/* Header Style */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Header Stili</h3>
            <div className="grid grid-cols-3 gap-3">
              {HEADER_STYLES.map((s) => (
                <button key={s.id} onClick={() => update("theme_header_style", s.id)}
                  className={`p-4 rounded-xl border-2 text-left transition-all ${
                    (settings.theme_header_style || "default") === s.id ? "border-primary shadow" : "border-border hover:border-primary/50"
                  }`}>
                  <h4 className="font-medium text-sm">{s.label}</h4>
                  <p className="text-xs text-muted-foreground mt-1">{s.desc}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Footer Style */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Footer Stili</h3>
            <div className="grid grid-cols-3 gap-3">
              {FOOTER_STYLES.map((s) => (
                <button key={s.id} onClick={() => update("theme_footer_style", s.id)}
                  className={`p-4 rounded-xl border-2 text-left transition-all ${
                    (settings.theme_footer_style || "default") === s.id ? "border-primary shadow" : "border-border hover:border-primary/50"
                  }`}>
                  <h4 className="font-medium text-sm">{s.label}</h4>
                  <p className="text-xs text-muted-foreground mt-1">{s.desc}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Product Card Style */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Urun Karti Stili</h3>
            <div className="grid grid-cols-3 gap-3">
              {CARD_STYLES.map((s) => (
                <button key={s.id} onClick={() => update("theme_product_card_style", s.id)}
                  className={`p-4 rounded-xl border-2 text-left transition-all ${
                    (settings.theme_product_card_style || "default") === s.id ? "border-primary shadow" : "border-border hover:border-primary/50"
                  }`}>
                  <h4 className="font-medium text-sm">{s.label}</h4>
                  <p className="text-xs text-muted-foreground mt-1">{s.desc}</p>
                </button>
              ))}
            </div>
          </div>

          {/* Grid Columns */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Urun Grid Sutun Sayisi</h3>
            <div className="flex gap-2">
              {["3", "4", "5"].map((n) => (
                <button key={n} onClick={() => update("theme_product_grid_columns", n)}
                  className={`px-6 py-2 rounded-lg text-sm border transition-colors ${
                    (settings.theme_product_grid_columns || "4") === n ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"
                  }`}>{n} Sutun</button>
              ))}
            </div>
          </div>

          {/* Border Radius */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Kose Yuvarlatma</h3>
            <div className="flex gap-2">
              {RADIUS_OPTIONS.map((r) => (
                <button key={r.id} onClick={() => update("theme_border_radius", r.id)}
                  className={`px-4 py-2 rounded-lg text-sm border transition-colors ${
                    (settings.theme_border_radius || "lg") === r.id ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"
                  }`}>{r.label}</button>
              ))}
            </div>
          </div>

          {/* Container Width */}
          <div>
            <h3 className="text-sm font-semibold mb-3">Sayfa Genisligi</h3>
            <div className="flex gap-2">
              {["1024", "1152", "1280", "1440"].map((w) => (
                <button key={w} onClick={() => update("theme_container_width", w)}
                  className={`px-4 py-2 rounded-lg text-sm border transition-colors ${
                    (settings.theme_container_width || "1280") === w ? "border-primary bg-primary/10 text-primary" : "border-border text-muted-foreground"
                  }`}>{w}px</button>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Advanced Tab */}
      {activeTab === "advanced" && (
        <div className="space-y-6">
          <div>
            <label className="flex items-center gap-3">
              <input type="checkbox" checked={settings.theme_dark_mode_enabled !== "false"}
                onChange={(e) => update("theme_dark_mode_enabled", e.target.checked ? "true" : "false")}
                className="w-4 h-4 rounded border-border" />
              <div>
                <span className="text-sm font-medium">Koyu Mod Toggle</span>
                <p className="text-xs text-muted-foreground">Kullanicilarin koyu mod gecisi yapabilmesini saglar</p>
              </div>
            </label>
          </div>

          <div>
            <label className="text-sm font-medium mb-2 block">Ozel CSS</label>
            <textarea value={settings.theme_custom_css || ""}
              onChange={(e) => update("theme_custom_css", e.target.value)}
              rows={8} placeholder="/* Ozel CSS kurallari */"
              className="w-full px-3 py-2 border border-border rounded-lg text-sm font-mono bg-background resize-y" />
          </div>

          <div className="flex gap-3">
            <button onClick={handleExport}
              className="px-4 py-2 border border-border rounded-lg text-sm hover:bg-muted transition-colors">
              Temayi Disa Aktar (JSON)
            </button>
            <label className="px-4 py-2 border border-border rounded-lg text-sm hover:bg-muted transition-colors cursor-pointer">
              Tema Ice Aktar
              <input type="file" accept=".json" onChange={handleImport} className="hidden" />
            </label>
          </div>
        </div>
      )}

      {/* Save Button */}
      <div className="flex items-center gap-3 pt-4 border-t border-border">
        <button onClick={handleSave} disabled={saving}
          className="px-6 py-2.5 bg-primary text-white rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50 transition-opacity">
          {saving ? "Kaydediliyor..." : "Kaydet"}
        </button>
        {saved && <span className="text-sm text-success">Tema ayarlari kaydedildi!</span>}
      </div>
    </div>
  );
}
